# 合并操作

In [1]:
import numpy as np
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [4]:
A = np.array([[1,2,3],
             [4,5,6]])
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [5]:
np.concatenate([A,A],axis=1) # axis=0按行进行拼接，否则按列进行拼接 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
z = np.array([666,666,666])
np.concatenate([A,z.reshape(1,-1)])  #两个矩阵维度要相同才能连接

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [8]:
np.vstack([A,z]) #在垂直方向进行矩阵的堆叠，不用维度相同

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [9]:
B = np.full((2,2),100) #在水平向进行矩阵的堆叠，不用维度相同
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

# 分割操作

In [19]:
x = np.arange(10)
x1,x2,x3 = np.split(x,[3,7]) #以下标0到3的元素作为分割点
x1

array([0, 1, 2])

In [14]:
x2

array([3, 4, 5, 6])

In [15]:
x3

array([7, 8, 9])

In [16]:
x1,x2 = np.split(x,[5])
x1

array([0, 1, 2, 3, 4])

In [17]:
x2

array([5, 6, 7, 8, 9])

In [20]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
A1,A2 = np.split(A,[2]) #默认是按行进行分割
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
A1,A2 = np.split(A,[2],axis=1) #默认是按行进行分割
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [24]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [27]:
upper, lower = np.vsplit(A,[2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
left, right = np.hsplit(A,[2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
right


array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [32]:
data = np.arange(16).reshape(4,4)
x,y = np.hsplit(data,[-1]) #分割出最后一列
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [33]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [38]:
y1 = y[:,0]
y1

array([ 3,  7, 11, 15])

In [39]:
y1.ndim


1

In [45]:
y1 = y.reshape(4)
y1


array([ 3,  7, 11, 15])

In [46]:
y1.ndim

1