# 基本属性

In [7]:
import numpy as np
x = np.arange(10)
np.reshape?

In [40]:
X = np.arange(15).reshape(3,5) #将一维矩阵变换成二维
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 基本属性

In [5]:
x.ndim #查看数组维度

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [12]:
x.size

10

In [13]:
X.size

15

 # numpy.array的数据访问

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[0]

0

In [17]:
X[(0,0)]

0

In [18]:
X[2,2]

12

In [20]:
x[0:5] #从0开始不包含5

array([0, 1, 2, 3, 4])

In [21]:
x[6:]

array([6, 7, 8, 9])

In [22]:
x[::-1] #最后一个参数为步长

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
X[:2,:3] #前两行前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [26]:
X[::-1,::-1] #矩阵反转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [27]:
X[0]

array([0, 1, 2, 3, 4])

In [28]:
X[0,:] #取行

array([0, 1, 2, 3, 4])

In [29]:
X[0,:].ndim

1

In [30]:
X[:,0] #取列

array([ 0,  5, 10])

In [35]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
subX[0,0] = 100 #改变子矩阵也会改变源矩阵
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [41]:
subX = X[:2,:3].copy()
subX[0,0] = 100 
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
x.shape

(10,)

In [43]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x1 = x.reshape(2,5)
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
B.shape

(1, 10)

In [51]:
B.ndim

2

In [52]:
B1 = x.reshape(10,-1)
B1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [53]:
B2 = x.reshape(-1,10)
B2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
B2.shape

(1, 10)

In [55]:
B1.shape


(10, 1)

In [56]:
x.reshape(2,-1) #-1表示自动匹配

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Object `np.arange.reshape` not found.
