# numpy中的矩阵运算gb

In [1]:
import numpy as np
L = np.arange(10)
A = np.array(2*L)#python中不能只能在数组中每个元素乘 
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [2]:
A +1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
A-1

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17])

In [4]:
A*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [5]:
1/A

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       , 0.08333333, 0.07142857, 0.0625    , 0.05555556])

In [6]:
np.abs(A)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.sin(A)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [8]:
np.cos(A)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671])

In [9]:
np.power(3,A)

array([        1,         9,        81,       729,      6561,     59049,
          531441,   4782969,  43046721, 387420489], dtype=int32)

In [10]:
3**A

array([        1,         9,        81,       729,      6561,     59049,
          531441,   4782969,  43046721, 387420489], dtype=int32)

In [11]:
np.log2(A)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([      -inf, 1.        , 2.        , 2.5849625 , 3.        ,
       3.32192809, 3.5849625 , 3.80735492, 4.        , 4.169925  ])

In [12]:
np.log10(A)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([      -inf, 0.30103   , 0.60205999, 0.77815125, 0.90308999,
       1.        , 1.07918125, 1.14612804, 1.20411998, 1.25527251])

## 矩阵运算

In [14]:
A=np.arange(4).reshape(2,2)
B= np.full((2,2),10)

In [15]:
A+B

array([[10, 11],
       [12, 13]])

In [16]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [17]:
A*B #对应元素相乘，不是矩阵的乘法

array([[ 0, 10],
       [20, 30]])

In [18]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [19]:
A.dot(B) #矩阵乘法

array([[10, 10],
       [50, 50]])

In [20]:
A.T #矩阵的转置

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [26]:
v = np.array([1,2])
v

array([1, 2])

In [31]:
A

array([[0, 1],
       [2, 3]])

In [27]:
A+v

array([[1, 3],
       [3, 5]])

In [23]:
np.tile(v,(2,1)) #矩阵的堆叠

array([[1, 2],
       [1, 2]])

In [28]:
A+v

array([[1, 3],
       [3, 5]])

In [29]:
v.dot(A)

array([4, 7])

In [30]:
v*A

array([[0, 2],
       [2, 6]])

In [33]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [34]:
A

array([[0, 1],
       [2, 3]])

In [35]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [37]:
invA = np.linalg.inv(A)
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [39]:
B = np.arange(16).reshape(2,8)
pinvB = np.linalg.pinv(B) #不是方阵求伪逆矩阵
B.dot(pinvB)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])