In [38]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

In [2]:
irirs = datasets.load_iris()

In [3]:
X = irirs.data
y = irirs.target

In [14]:
irirs.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
X.shape

(150, 4)

In [16]:
y.shape

(150,)

In [17]:
y #需要乱序

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
shuffle_indexes = np.random.permutation(len(X))

In [19]:
shuffle_indexes

array([ 68,  20,  88,  75,  34,  38,  96, 148, 108,  66, 124,   4,  78,
        13,   9, 102,  36,  39,  52,  81, 118,  87,  56,  22, 136,  47,
       114,  42, 144, 131,   5, 121, 133, 146,  23, 112, 116, 115, 123,
       140, 119, 135,  98,  37,  77,  82,  79,  92,  70,   2,   1,  25,
        65,  86,  51,   0, 139,  97,  41,  91,  71,  60, 125, 142,  27,
        50, 127,  19, 103, 122, 130,  57,  69,  89,   7,  95,  55, 143,
        16, 138, 100,  48,  93,  15,  53,  10, 113,  14,  17, 134,  18,
        94,  90,  49,  74,  28, 110, 128,  99,  84, 137,  45,  62,  30,
       105,  26,  61, 147,   3,   6,  24, 101,  76,  80,  54, 106,  35,
       145, 104,  21, 120,  29,  85,  67,  43,  31, 126, 149,  12,  11,
       107,  32,  59,  64, 111, 132,  44,  83, 109,  46,  33,  58, 141,
        40, 129, 117,  72,  73,   8,  63])

In [25]:
test_ratio = 0.2

In [26]:
test_size = int(len(X)*test_ratio)

In [27]:

test_size

30

In [29]:
test_indexes = shuffle_indexes[:test_size]

In [28]:
train_indexes = shuffle_indexes[test_size:]

In [35]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [36]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [43]:
K_classifier = KNeighborsClassifier(n_neighbors=6)
K_classifier.fit(X_train,y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [51]:
x = np.array([8.093607318, 3.365731514])
x_predict = x.reshape(1,-1)
x_predict

array([[8.09360732, 3.36573151]])

In [53]:
K_classifier.predict(X_test)

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 1, 2, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 1,
       1, 0, 2, 0, 2, 0, 2, 2])